/* Rezeptsammlung. Salz, Pfeffer, Öl, Zucker und Gewürze werden als Grundvorrat vorausgesetzt.
   ingredients = nötig, optional = passt gut dazu. Schlüssel siehe INGREDIENTS in logic.js. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.FridgeRecipes = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  const BASE = [
    { id: 'ruehrei', name: 'Rührei mit Brot', emoji: '🍳', minutes: 10,
      ingredients: ['eier', 'brot'], optional: ['milch', 'schinken', 'tomaten', 'kaese', 'speck'],
      steps: ['Eier mit einem Schuss Milch, Salz und Pfeffer verquirlen.', 'In Butter oder Öl bei mittlerer Hitze langsam stocken lassen, dabei rühren.', 'Nach Belieben Schinken, Tomaten oder Käse unterheben und mit Brot servieren.'] },
    { id: 'omelett', name: 'Gemüse-Omelett', emoji: '🍳', minutes: 15,
      ingredients: ['eier', 'paprika'], optional: ['zwiebeln', 'champignons', 'spinat', 'kaese', 'tomaten', 'zucchini'],
      steps: ['Gemüse klein schneiden und in der Pfanne 3–4 Minuten anbraten.', 'Eier verquirlen, würzen und über das Gemüse gießen.', 'Bei kleiner Hitze mit Deckel stocken lassen, ggf. Käse darüberstreuen.'] },
    { id: 'pfannkuchen', name: 'Pfannkuchen', emoji: '🥞', minutes: 25,
      ingredients: ['mehl', 'eier', 'milch'], optional: ['aepfel', 'bananen', 'beeren', 'schokolade'],
      steps: ['250 g Mehl, 3 Eier, 500 ml Milch und eine Prise Salz glatt rühren, 10 Min. quellen lassen.', 'Dünn in einer gefetteten Pfanne von beiden Seiten goldbraun backen.', 'Mit Obst, Zucker & Zimt oder Schokolade servieren.'] },
    { id: 'french-toast', name: 'Arme Ritter (French Toast)', emoji: '🍞', minutes: 15,
      ingredients: ['brot', 'eier', 'milch'], optional: ['beeren', 'bananen', 'aepfel'],
      steps: ['Eier mit Milch, etwas Zucker und Zimt verquirlen.', 'Altbackenes Brot darin einweichen.', 'In Butter goldbraun braten, mit Obst servieren.'] },
    { id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', emoji: '🍝', minutes: 40,
      ingredients: ['nudeln', 'hackfleisch', 'passata'], optional: ['zwiebeln', 'knoblauch', 'karotten', 'parmesan'],
      steps: ['Zwiebel, Knoblauch und Karotte fein würfeln und anschwitzen.', 'Hackfleisch krümelig braten, Tomaten zugeben, 20 Min. köcheln, würzen.', 'Nudeln kochen und mit Soße und Parmesan servieren.'] },
    { id: 'pasta-tomate', name: 'Pasta mit Tomatensoße', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'passata'], optional: ['zwiebeln', 'knoblauch', 'mozzarella', 'parmesan', 'tomaten'],
      steps: ['Zwiebel und Knoblauch in Olivenöl anschwitzen.', 'Tomaten zugeben, mit Salz, Pfeffer, Zucker und Oregano 10 Min. köcheln.', 'Mit den gekochten Nudeln mischen, Käse darüber.'] },
    { id: 'carbonara', name: 'Spaghetti Carbonara', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'eier', 'speck', 'parmesan'], optional: ['sahne'],
      steps: ['Nudeln kochen. Speck knusprig braten.', 'Eigelb mit geriebenem Parmesan und Pfeffer verrühren.', 'Heiße Nudeln mit Speck mischen, Topf vom Herd, Eimasse und etwas Nudelwasser unterrühren.'] },
    { id: 'pasta-sahne-schinken', name: 'Nudeln in Schinken-Sahne-Soße', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'sahne', 'schinken'], optional: ['erbsen', 'champignons', 'kaese', 'zwiebeln'],
      steps: ['Zwiebel und Schinken in Würfeln anbraten.', 'Sahne zugießen, aufkochen, mit Salz, Pfeffer und Muskat würzen.', 'Erbsen/Pilze kurz mitgaren und mit den Nudeln vermengen.'] },
    { id: 'pasta-spinat', name: 'Pasta mit Spinat und Feta', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'spinat', 'feta'], optional: ['knoblauch', 'tomaten', 'sahne'],
      steps: ['Nudeln kochen.', 'Knoblauch anschwitzen, Spinat zusammenfallen lassen.', 'Feta zerbröseln, mit Nudeln und etwas Nudelwasser mischen.'] },
    { id: 'pesto-pasta', name: 'Pesto-Pasta', emoji: '🌿', minutes: 15,
      ingredients: ['nudeln', 'pesto'], optional: ['tomaten', 'parmesan', 'mozzarella', 'haehnchen'],
      steps: ['Nudeln kochen, etwas Nudelwasser aufheben.', 'Mit Pesto und einem Schluck Nudelwasser vermengen.', 'Mit Tomaten und Parmesan servieren.'] },
    { id: 'lasagne', name: 'Gemüse-Lasagne', emoji: '🧀', minutes: 60,
      ingredients: ['nudeln', 'zucchini', 'passata', 'kaese'], optional: ['paprika', 'spinat', 'milch', 'zwiebeln'],
      steps: ['Gemüse würfeln, anbraten, Tomaten zugeben und würzen.', 'Abwechselnd Lasagneplatten, Gemüsesoße und Käse schichten.', 'Bei 180 °C ca. 35 Min. backen.'] },
    { id: 'gnocchi-pfanne', name: 'Gnocchi-Pfanne mit Tomate & Mozzarella', emoji: '🥟', minutes: 20,
      ingredients: ['gnocchi', 'tomaten'], optional: ['mozzarella', 'spinat', 'zucchini', 'pesto', 'knoblauch'],
      steps: ['Gnocchi in Öl goldbraun braten.', 'Tomaten und Gemüse zugeben, kurz mitbraten, würzen.', 'Mozzarella darauf zerpflücken und mit Deckel schmelzen lassen.'] },
    { id: 'gebratener-reis', name: 'Gebratener Reis', emoji: '🍚', minutes: 20,
      ingredients: ['reis', 'eier'], optional: ['erbsen', 'karotten', 'paprika', 'schinken', 'haehnchen', 'lauch', 'mais'],
      steps: ['Am besten Reis vom Vortag verwenden.', 'Gemüse in heißem Öl scharf anbraten, Reis zugeben.', 'Eier unterrühren, mit Sojasoße abschmecken.'] },
    { id: 'curry', name: 'Gemüse-Curry mit Kokosmilch', emoji: '🍛', minutes: 30,
      ingredients: ['kokosmilch', 'reis'], optional: ['haehnchen', 'paprika', 'zucchini', 'brokkoli', 'karotten', 'kichererbsen', 'tofu', 'spinat', 'kuerbis', 'blumenkohl'],
      steps: ['Zwiebel, Knoblauch und Currypaste/-pulver anschwitzen.', 'Gemüse (und ggf. Fleisch/Tofu) zugeben, mit Kokosmilch ablöschen.', '15 Min. köcheln lassen, mit Reis servieren.'] },
    { id: 'haehnchen-gemuese', name: 'Hähnchen-Gemüse-Pfanne', emoji: '🍗', minutes: 25,
      ingredients: ['haehnchen', 'paprika'], optional: ['zucchini', 'brokkoli', 'reis', 'zwiebeln', 'champignons', 'karotten'],
      steps: ['Hähnchen in Streifen schneiden und scharf anbraten, herausnehmen.', 'Gemüse in der gleichen Pfanne braten.', 'Fleisch zurückgeben, würzen, mit Reis servieren.'] },
    { id: 'risotto', name: 'Pilzrisotto', emoji: '🍄', minutes: 35,
      ingredients: ['reis', 'champignons', 'parmesan'], optional: ['zwiebeln', 'butter', 'spinat'],
      steps: ['Zwiebel anschwitzen, Reis glasig dünsten.', 'Nach und nach heiße Brühe angießen und rühren, bis der Reis cremig ist (ca. 20 Min.).', 'Gebratene Pilze, Butter und Parmesan unterziehen.'] },
    { id: 'chili', name: 'Chili con Carne', emoji: '🌶️', minutes: 45,
      ingredients: ['hackfleisch', 'bohnen', 'passata'], optional: ['mais', 'paprika', 'zwiebeln', 'reis', 'brot'],
      steps: ['Hack mit Zwiebeln krümelig braten, mit Kreuzkümmel und Chili würzen.', 'Tomaten, Bohnen, Mais und Paprika zugeben.', '30 Min. köcheln, mit Reis oder Brot servieren.'] },
    { id: 'chili-sin-carne', name: 'Chili sin Carne', emoji: '🌶️', minutes: 35,
      ingredients: ['bohnen', 'passata', 'mais'], optional: ['linsen', 'paprika', 'zwiebeln', 'reis', 'karotten'],
      steps: ['Zwiebeln, Paprika und Karotten anbraten.', 'Tomaten, Bohnen, Mais (und rote Linsen) zugeben, kräftig würzen.', '20 Min. köcheln lassen.'] },
    { id: 'wraps', name: 'Gefüllte Wraps', emoji: '🌯', minutes: 20,
      ingredients: ['wraps', 'salat'], optional: ['haehnchen', 'tomaten', 'gurke', 'kaese', 'mais', 'paprika', 'bohnen', 'feta', 'frischkaese'],
      steps: ['Füllung vorbereiten: Fleisch braten, Gemüse schneiden.', 'Wraps kurz in der Pfanne erwärmen und mit Frischkäse oder Joghurtsoße bestreichen.', 'Füllen, einrollen, halbieren.'] },
    { id: 'quesadillas', name: 'Quesadillas', emoji: '🌮', minutes: 15,
      ingredients: ['wraps', 'kaese'], optional: ['mais', 'bohnen', 'paprika', 'haehnchen', 'zwiebeln'],
      steps: ['Eine Hälfte des Wraps mit Käse und Füllung belegen.', 'Zusammenklappen und in der Pfanne ohne Fett von beiden Seiten knusprig braten.', 'In Stücke schneiden.'] },
    { id: 'bratkartoffeln', name: 'Bratkartoffeln mit Spiegelei', emoji: '🥔', minutes: 30,
      ingredients: ['kartoffeln', 'eier'], optional: ['zwiebeln', 'speck', 'gurke'],
      steps: ['Gekochte Kartoffeln in Scheiben schneiden.', 'Mit Zwiebeln und Speck in Öl knusprig braten.', 'Spiegeleier dazu braten.'] },
    { id: 'kartoffelsuppe', name: 'Kartoffelsuppe', emoji: '🍲', minutes: 40,
      ingredients: ['kartoffeln', 'karotten'], optional: ['lauch', 'wurst', 'sahne', 'zwiebeln', 'speck'],
      steps: ['Kartoffeln, Karotten und Lauch würfeln, in Brühe 20 Min. kochen.', 'Teilweise pürieren, mit Sahne, Majoran und Muskat abschmecken.', 'Würstchen in Scheiben darin erwärmen.'] },
    { id: 'kartoffelgratin', name: 'Kartoffelgratin', emoji: '🥔', minutes: 60,
      ingredients: ['kartoffeln', 'sahne', 'kaese'], optional: ['milch', 'knoblauch', 'brokkoli', 'schinken'],
      steps: ['Kartoffeln dünn hobeln und in eine Form schichten.', 'Sahne/Milch mit Knoblauch, Salz und Muskat darübergießen, Käse obenauf.', 'Bei 180 °C ca. 45 Min. backen.'] },
    { id: 'ofengemuese', name: 'Ofengemüse mit Feta', emoji: '🥕', minutes: 40,
      ingredients: ['kartoffeln', 'paprika', 'feta'], optional: ['zucchini', 'karotten', 'zwiebeln', 'kuerbis', 'tomaten', 'joghurt'],
      steps: ['Gemüse in Stücke schneiden, mit Öl, Salz, Paprika und Kräutern mischen.', 'Bei 200 °C ca. 30 Min. rösten, Feta darüberbröseln, 5 Min. weiter backen.', 'Mit Joghurt-Dip servieren.'] },
    { id: 'kuerbissuppe', name: 'Kürbissuppe', emoji: '🎃', minutes: 35,
      ingredients: ['kuerbis', 'zwiebeln'], optional: ['karotten', 'kokosmilch', 'sahne', 'kartoffeln'],
      steps: ['Kürbis (Hokkaido mit Schale), Zwiebel und Karotte würfeln.', 'Anschwitzen, mit Brühe bedecken, 20 Min. kochen.', 'Pürieren, mit Kokosmilch oder Sahne, Ingwer und Curry abschmecken.'] },
    { id: 'gemuesesuppe', name: 'Bunte Gemüsesuppe', emoji: '🍲', minutes: 35,
      ingredients: ['karotten', 'lauch'], optional: ['kartoffeln', 'zucchini', 'erbsen', 'blumenkohl', 'nudeln', 'brokkoli', 'wurst'],
      steps: ['Gemüse klein schneiden und in Öl anschwitzen.', 'Mit Brühe aufgießen, 20 Min. köcheln.', 'Nach Belieben Suppennudeln oder Würstchen zugeben.'] },
    { id: 'linsensuppe', name: 'Rote Linsensuppe', emoji: '🥣', minutes: 30,
      ingredients: ['linsen', 'karotten'], optional: ['zwiebeln', 'kokosmilch', 'zitrone', 'passata'],
      steps: ['Zwiebel und Karotte anschwitzen, Linsen zugeben.', 'Mit Brühe auffüllen, 15 Min. kochen, pürieren.', 'Mit Kreuzkümmel, Zitrone und Kokosmilch abschmecken.'] },
    { id: 'brokkoli-auflauf', name: 'Brokkoli-Nudel-Auflauf', emoji: '🥦', minutes: 45,
      ingredients: ['brokkoli', 'nudeln', 'kaese'], optional: ['schinken', 'sahne', 'milch', 'eier'],
      steps: ['Nudeln und Brokkoli bissfest garen.', 'Mit Schinken in eine Form geben, Sahne mit Ei verquirlt darübergießen.', 'Mit Käse bestreuen, bei 200 °C 20 Min. überbacken.'] },
    { id: 'blumenkohl-kaese', name: 'Blumenkohl mit Käsesoße', emoji: '🥦', minutes: 30,
      ingredients: ['blumenkohl', 'kaese', 'milch'], optional: ['butter', 'mehl', 'kartoffeln', 'schinken'],
      steps: ['Blumenkohl in Röschen in Salzwasser garen.', 'Mehlschwitze aus Butter und Mehl, mit Milch aufgießen, Käse darin schmelzen.', 'Soße über den Blumenkohl geben.'] },
    { id: 'shakshuka', name: 'Shakshuka', emoji: '🍳', minutes: 25,
      ingredients: ['eier', 'passata', 'paprika'], optional: ['zwiebeln', 'knoblauch', 'feta', 'brot', 'tomaten'],
      steps: ['Zwiebel, Knoblauch und Paprika anbraten, mit Kreuzkümmel und Paprikapulver würzen.', 'Tomaten zugeben und 10 Min. einkochen.', 'Mulden formen, Eier hineinschlagen und zugedeckt stocken lassen. Mit Feta und Brot.'] },
    { id: 'lachs-ofen', name: 'Lachs aus dem Ofen mit Gemüse', emoji: '🐟', minutes: 30,
      ingredients: ['lachs', 'kartoffeln'], optional: ['zitrone', 'brokkoli', 'zucchini', 'sahne', 'spinat'],
      steps: ['Kartoffeln vorkochen oder klein geschnitten 15 Min. vorbacken.', 'Lachs und Gemüse dazulegen, mit Zitrone, Salz und Dill würzen.', 'Bei 200 °C ca. 15 Min. garen.'] },
    { id: 'fischpfanne', name: 'Fischfilet mit Reis und Gemüse', emoji: '🐟', minutes: 25,
      ingredients: ['fisch', 'reis'], optional: ['zitrone', 'erbsen', 'karotten', 'butter', 'spinat'],
      steps: ['Reis kochen.', 'Fischfilet salzen, in Mehl wenden und in Butter braten.', 'Gemüse dünsten, mit Zitrone servieren.'] },
    { id: 'thunfisch-pasta', name: 'Thunfisch-Tomaten-Pasta', emoji: '🐟', minutes: 20,
      ingredients: ['nudeln', 'thunfisch', 'passata'], optional: ['zwiebeln', 'mais', 'zitrone', 'knoblauch'],
      steps: ['Zwiebel und Knoblauch anschwitzen, Tomaten zugeben.', 'Thunfisch zerpflückt unterrühren, 5 Min. köcheln.', 'Mit Nudeln mischen.'] },
    { id: 'schnitzel', name: 'Schnitzel mit Kartoffelsalat', emoji: '🥩', minutes: 45,
      ingredients: ['schwein', 'eier', 'kartoffeln'], optional: ['mehl', 'brot', 'gurke', 'zitrone', 'zwiebeln'],
      steps: ['Kartoffeln kochen, schneiden, mit Brühe, Essig, Öl und Zwiebeln anmachen.', 'Schnitzel klopfen, in Mehl, Ei und Semmelbröseln wenden.', 'In reichlich Fett goldbraun braten.'] },
    { id: 'gulasch', name: 'Rindergulasch', emoji: '🥩', minutes: 120,
      ingredients: ['rind', 'zwiebeln'], optional: ['paprika', 'passata', 'kartoffeln', 'nudeln'],
      steps: ['Fleisch portionsweise scharf anbraten.', 'Viele Zwiebeln mitbraten, Paprikapulver und Tomatenmark zugeben.', 'Mit Brühe ablöschen und 1,5 Std. schmoren.'] },
    { id: 'griechischer-salat', name: 'Griechischer Salat', emoji: '🥗', minutes: 10,
      ingredients: ['tomaten', 'gurke', 'feta'], optional: ['paprika', 'zwiebeln', 'salat', 'brot'],
      steps: ['Tomaten, Gurke, Paprika und Zwiebel grob schneiden.', 'Mit Olivenöl, Essig, Oregano, Salz und Pfeffer anmachen.', 'Feta obenauf.'] },
    { id: 'caprese', name: 'Tomate-Mozzarella', emoji: '🍅', minutes: 5,
      ingredients: ['tomaten', 'mozzarella'], optional: ['pesto', 'brot', 'salat'],
      steps: ['Tomaten und Mozzarella in Scheiben schneiden.', 'Abwechselnd anrichten, mit Salz, Pfeffer, Olivenöl und Basilikum/Pesto.'] },
    { id: 'gemischter-salat', name: 'Gemischter Salat', emoji: '🥗', minutes: 10,
      ingredients: ['salat', 'tomaten'], optional: ['gurke', 'paprika', 'karotten', 'mais', 'eier', 'thunfisch', 'kaese', 'feta'],
      steps: ['Salat waschen und zupfen, Gemüse schneiden.', 'Dressing aus Öl, Essig, Senf, Salz, Pfeffer und etwas Zucker.', 'Mit Ei, Thunfisch oder Käse zur Hauptmahlzeit machen.'] },
    { id: 'zucchini-puffer', name: 'Zucchini-Puffer mit Joghurt-Dip', emoji: '🥒', minutes: 30,
      ingredients: ['zucchini', 'eier', 'mehl'], optional: ['feta', 'kaese', 'joghurt', 'knoblauch', 'karotten'],
      steps: ['Zucchini raspeln, salzen, 10 Min. ziehen lassen und ausdrücken.', 'Mit Ei, Mehl und Feta/Käse mischen.', 'Kleine Puffer goldbraun braten, Joghurt mit Knoblauch als Dip.'] },
    { id: 'pizza-toast', name: 'Pizza-Toast', emoji: '🍕', minutes: 15,
      ingredients: ['brot', 'kaese'], optional: ['schinken', 'passata', 'tomaten', 'paprika', 'champignons', 'mais', 'wurst'],
      steps: ['Brot mit Tomatenmark oder -soße bestreichen.', 'Belegen und mit Käse bestreuen.', 'Bei 200 °C ca. 10 Min. überbacken.'] },
    { id: 'kaesespaetzle', name: 'Käse-Nudeln mit Röstzwiebeln', emoji: '🧀', minutes: 25,
      ingredients: ['nudeln', 'kaese', 'zwiebeln'], optional: ['speck', 'butter', 'salat'],
      steps: ['Zwiebeln in Ringen in Butter langsam goldbraun braten.', 'Nudeln kochen und abwechselnd mit Käse in eine Pfanne/Form schichten.', 'Mit Zwiebeln servieren, dazu Salat.'] },
    { id: 'overnight-oats', name: 'Overnight Oats', emoji: '🥣', minutes: 5,
      ingredients: ['haferflocken', 'joghurt'], optional: ['milch', 'beeren', 'bananen', 'aepfel'],
      steps: ['Haferflocken mit Joghurt und Milch 1:1:1 mischen.', 'Über Nacht in den Kühlschrank stellen.', 'Mit Obst toppen.'] },
    { id: 'quark-dessert', name: 'Quarkspeise mit Obst', emoji: '🍓', minutes: 10,
      ingredients: ['quark', 'beeren'], optional: ['joghurt', 'sahne', 'bananen', 'zitrone'],
      steps: ['Quark mit Joghurt oder geschlagener Sahne glatt rühren.', 'Mit Zucker/Vanille und Zitrone abschmecken.', 'Obst unterheben oder darauf verteilen.'] },
    { id: 'smoothie', name: 'Smoothie', emoji: '🥤', minutes: 5,
      ingredients: ['bananen', 'milch'], optional: ['beeren', 'joghurt', 'haferflocken', 'spinat', 'aepfel'],
      steps: ['Alles in den Mixer geben.', 'Fein pürieren und sofort trinken – ideal für sehr reifes Obst.'] },
    { id: 'bananenbrot', name: 'Bananenbrot', emoji: '🍌', minutes: 70,
      ingredients: ['bananen', 'mehl', 'eier'], optional: ['butter', 'haferflocken', 'schokolade'],
      steps: ['3 sehr reife Bananen zerdrücken, mit 2 Eiern, 80 g Butter und 80 g Zucker verrühren.', '250 g Mehl mit 1 Pck. Backpulver unterheben.', 'In einer Kastenform bei 175 °C ca. 50 Min. backen.'] },
    { id: 'apfelkuchen', name: 'Schneller Apfelkuchen', emoji: '🍎', minutes: 60,
      ingredients: ['aepfel', 'mehl', 'eier', 'butter'], optional: ['zitrone', 'quark'],
      steps: ['Rührteig aus 200 g Butter, 150 g Zucker, 3 Eiern und 250 g Mehl mit Backpulver.', 'In die Form geben, mit Apfelspalten belegen.', 'Bei 180 °C ca. 40 Min. backen.'] },
    ];

  /** Kategorien der ursprünglichen Rezepte (Standard: Hauptgericht). */
  const BASE_CAT = {
    ruehrei: 'fruehstueck', omelett: 'fruehstueck', 'french-toast': 'fruehstueck', 'overnight-oats': 'fruehstueck', smoothie: 'fruehstueck',
    pfannkuchen: 'suess', 'quark-dessert': 'suess', bananenbrot: 'suess', apfelkuchen: 'suess',
    kartoffelsuppe: 'suppe', kuerbissuppe: 'suppe', gemuesesuppe: 'suppe', linsensuppe: 'suppe',
    'griechischer-salat': 'salat', caprese: 'salat', 'gemischter-salat': 'salat',
    quesadillas: 'snack', 'pizza-toast': 'snack', wraps: 'snack',
  };

  // Kompakt: [id, Name, Emoji, Minuten, Kategorie, Zutaten, passt dazu, Schritte (mit | getrennt)]
  const MORE = [
    // ---------- Frühstück ----------
    ['porridge', 'Porridge mit Obst', '🥣', 10, 'fruehstueck', 'haferflocken milch', 'bananen beeren aepfel', '50 g Haferflocken mit 250 ml Milch und einer Prise Salz aufkochen.|Unter Rühren 3–5 Min. köcheln, bis es cremig ist.|Mit Obst, etwas Zimt oder Honig servieren.'],
    ['bircher', 'Bircher Müsli', '🍏', 10, 'fruehstueck', 'haferflocken joghurt aepfel', 'zitrone beeren milch', 'Haferflocken mit Joghurt und einem Schuss Milch verrühren.|Apfel grob dazureiben, mit Zitronensaft beträufeln.|Am besten über Nacht ziehen lassen, morgens mit Beeren toppen.'],
    ['avocado-toast', 'Avocado-Toast mit Ei', '🥑', 10, 'fruehstueck', 'brot avocado', 'eier tomaten zitrone feta', 'Brot toasten.|Avocado mit Zitrone, Salz und Pfeffer zerdrücken und aufstreichen.|Mit Spiegel- oder pochiertem Ei, Tomaten oder Feta belegen.'],
    ['quarkbrot', 'Quarkbrot mit Gurke', '🥒', 5, 'fruehstueck', 'brot quark', 'gurke tomaten zwiebeln', 'Quark mit Salz, Pfeffer und Kräutern glatt rühren.|Dick aufs Brot streichen.|Mit Gurken- und Tomatenscheiben belegen.'],
    ['bananen-pancakes', 'Bananen-Pancakes (ohne Mehl)', '🍌', 15, 'fruehstueck', 'bananen eier', 'haferflocken beeren', '1 reife Banane mit 2 Eiern zerdrücken und verquirlen, nach Wunsch 2 EL Haferflocken dazu.|Kleine Pancakes in etwas Butter bei mittlerer Hitze von beiden Seiten backen.|Mit Beeren servieren.'],
    ['joghurt-bowl', 'Joghurt-Bowl', '🫐', 5, 'fruehstueck', 'joghurt beeren', 'haferflocken bananen aepfel', 'Joghurt in eine Schale geben.|Mit Obst und Haferflocken (oder Müsli) toppen.|Mit etwas Honig süßen.'],
    ['frittata', 'Gemüse-Frittata', '🍳', 25, 'fruehstueck', 'eier zucchini', 'paprika kaese kartoffeln zwiebeln spinat', 'Gemüse klein schneiden und in einer ofenfesten Pfanne anbraten.|6 Eier verquirlen, würzen, darübergießen und Käse darauf streuen.|Kurz auf dem Herd stocken lassen, dann bei 200 °C ca. 10 Min. im Ofen fertig garen.'],
    ['schinken-kaese-toast', 'Schinken-Käse-Toast', '🥪', 15, 'snack', 'brot schinken kaese', 'tomaten butter', 'Brot dünn mit Butter bestreichen.|Mit Schinken, Tomate und Käse belegen.|Bei 200 °C ca. 8 Min. überbacken oder im Sandwichmaker toasten.'],
    ['eiersalat', 'Eiersalat', '🥚', 20, 'salat', 'eier joghurt', 'gurke zwiebeln brot sauresahne', 'Eier 10 Min. hart kochen, abschrecken, pellen und würfeln.|Mit Joghurt (oder Schmand), Salz, Pfeffer und etwas Senf verrühren.|Gewürfelte Gurke und Zwiebel unterheben – passt aufs Brot.'],
    ['bauernfruehstueck', 'Bauernfrühstück', '🥔', 25, 'haupt', 'kartoffeln eier speck', 'zwiebeln gurke', 'Gekochte Kartoffeln in Scheiben mit Speck und Zwiebeln knusprig braten.|Eier verquirlen, würzen und darübergießen.|Stocken lassen, mit Gewürzgurken servieren.'],
    ['kaiserschmarrn', 'Kaiserschmarrn', '🥞', 25, 'suess', 'mehl eier milch', 'aepfel butter beeren', '125 g Mehl, 250 ml Milch, 3 Eigelb und eine Prise Salz verrühren, steif geschlagenes Eiweiß unterheben.|In Butter backen, wenden und mit zwei Gabeln zerreißen.|Mit etwas Zucker karamellisieren, mit Apfelmus oder Beeren servieren.'],
    ['milchreis', 'Milchreis', '🍚', 35, 'suess', 'reis milch', 'aepfel beeren zitrone butter', '125 g Milchreis (oder Rundkornreis) mit 600 ml Milch, Prise Salz und 2 EL Zucker aufkochen.|Bei kleinster Hitze ca. 30 Min. quellen lassen, öfter umrühren.|Mit Zimt und Zucker, Kompott oder Beeren servieren.'],

    // ---------- Pasta & Gnocchi ----------
    ['aglio-olio', 'Spaghetti Aglio e Olio', '🧄', 15, 'haupt', 'nudeln knoblauch', 'parmesan zitrone', 'Spaghetti kochen.|Knoblauch in Scheiben in reichlich Olivenöl langsam goldgelb werden lassen, Chili dazu.|Nudeln mit etwas Nudelwasser im Öl schwenken, mit Parmesan servieren.'],
    ['pasta-brokkoli', 'Pasta mit Brokkoli-Sahne', '🥦', 20, 'haupt', 'nudeln brokkoli sahne', 'parmesan knoblauch', 'Brokkoli-Röschen die letzten 4 Min. mit den Nudeln kochen.|Knoblauch anschwitzen, Sahne zugießen, mit Salz, Pfeffer und Muskat würzen.|Nudeln und Brokkoli untermischen, Parmesan darüber.'],
    ['lachs-pasta', 'Lachs-Sahne-Pasta', '🐟', 25, 'haupt', 'nudeln lachs sahne', 'zitrone spinat knoblauch', 'Nudeln kochen.|Lachs in Würfeln kurz anbraten, mit Sahne ablöschen, Spinat zusammenfallen lassen.|Mit Zitrone, Salz und Pfeffer abschmecken und mit den Nudeln mischen.'],
    ['zucchini-pasta', 'Zucchini-Zitronen-Pasta', '🍋', 20, 'haupt', 'nudeln zucchini', 'zitrone parmesan knoblauch frischkaese', 'Nudeln kochen.|Zucchini grob raspeln und mit Knoblauch 3 Min. in Olivenöl braten.|Mit Zitronenabrieb, Frischkäse, Nudelwasser und den Nudeln vermengen, Parmesan darüber.'],
    ['pilz-pasta', 'Pasta mit Pilzrahm', '🍄', 20, 'haupt', 'nudeln champignons sahne', 'zwiebeln parmesan schinken', 'Nudeln kochen.|Pilze und Zwiebeln kräftig anbraten, mit Sahne ablöschen und einköcheln.|Würzen und mit den Nudeln mischen.'],
    ['mac-cheese', 'Mac and Cheese', '🧀', 30, 'haupt', 'nudeln kaese milch', 'butter mehl speck brokkoli', 'Makkaroni bissfest kochen.|Aus 2 EL Butter, 2 EL Mehl und 400 ml Milch eine Soße kochen, 150 g Käse darin schmelzen.|Nudeln unterheben, mit Käse bestreuen und kurz überbacken.'],
    ['schinkennudeln', 'Überbackene Schinkennudeln', '🍝', 35, 'haupt', 'nudeln schinken eier kaese', 'sahne erbsen zwiebeln', 'Nudeln kochen und mit Schinkenwürfeln (und Erbsen) in eine Form geben.|Eier mit Sahne oder Milch, Salz und Pfeffer verquirlen und darübergießen.|Mit Käse bestreuen, bei 200 °C ca. 20 Min. backen.'],
    ['feta-pasta', 'Ofen-Feta-Pasta', '🍅', 35, 'haupt', 'nudeln feta tomaten', 'knoblauch spinat', 'Cherrytomaten und Knoblauch in eine Form geben, Feta in die Mitte, mit Olivenöl beträufeln.|Bei 200 °C 25 Min. backen.|Alles zerdrücken und mit den gekochten Nudeln (und Spinat) vermengen.'],
    ['kuerbis-pasta', 'Kürbis-Pasta', '🎃', 30, 'haupt', 'nudeln kuerbis sahne', 'zwiebeln parmesan spinat', 'Kürbis würfeln, mit Zwiebel anbraten, mit etwas Wasser weich dünsten.|Mit Sahne pürieren, mit Muskat, Salz und Pfeffer würzen.|Mit den Nudeln mischen, Parmesan darüber.'],
    ['nudelpfanne-wurst', 'Nudelpfanne mit Würstchen', '🌭', 20, 'haupt', 'nudeln wurst passata', 'paprika zwiebeln kaese', 'Nudeln kochen.|Würstchen in Scheiben mit Zwiebel und Paprika anbraten.|Tomatensoße und Nudeln dazugeben, würzen, mit Käse servieren.'],
    ['lasagne-bolognese', 'Lasagne Bolognese', '🍝', 75, 'haupt', 'nudeln hackfleisch passata kaese', 'milch butter mehl zwiebeln karotten', 'Bolognese aus Hack, Zwiebel, Karotte und Tomaten 20 Min. köcheln.|Béchamel aus Butter, Mehl und Milch kochen.|Platten, Soße und Béchamel schichten, mit Käse abschließen, bei 180 °C 40 Min. backen.'],
    ['nudelsalat', 'Nudelsalat', '🥗', 25, 'salat', 'nudeln gurke', 'mais schinken kaese joghurt paprika erbsen tomaten', 'Nudeln kochen und abschrecken.|Gemüse, Schinken und Käse würfeln.|Mit Joghurt-Dressing (oder Essig und Öl) anmachen und ziehen lassen.'],
    ['one-pot-pasta', 'One-Pot-Pasta', '🍲', 25, 'haupt', 'nudeln tomaten zwiebeln', 'knoblauch spinat parmesan mozzarella', 'Rohe Nudeln, Tomaten, Zwiebel, Knoblauch und ca. 800 ml Wasser mit Salz in einen Topf geben.|Aufkochen und unter häufigem Rühren ca. 12 Min. köcheln, bis die Flüssigkeit fast weg ist.|Spinat unterrühren, mit Käse servieren.'],
    ['gnocchi-spinat', 'Gnocchi in Spinat-Sahne', '🥟', 20, 'haupt', 'gnocchi spinat sahne', 'parmesan knoblauch', 'Gnocchi in Butter goldbraun braten.|Knoblauch und Spinat dazugeben, mit Sahne ablöschen.|Mit Muskat und Parmesan abschmecken.'],
    ['gnocchi-auflauf', 'Gnocchi-Auflauf', '🧀', 35, 'haupt', 'gnocchi passata mozzarella', 'zucchini paprika knoblauch', 'Gnocchi roh mit Tomatensoße und Gemüse in eine Form geben.|Mozzarella darauf zupfen.|Bei 200 °C ca. 25 Min. backen.'],
    ['garnelen-pasta', 'Knoblauch-Garnelen-Pasta', '🦐', 20, 'haupt', 'nudeln fisch knoblauch', 'zitrone tomaten', 'Nudeln kochen.|Garnelen mit viel Knoblauch und Chili in Olivenöl 3 Min. braten.|Mit Zitrone, Nudeln und etwas Nudelwasser schwenken.'],

    // ---------- Reis ----------
    ['reispfanne', 'Gemüse-Reispfanne', '🍚', 25, 'haupt', 'reis paprika zucchini', 'mais erbsen eier karotten', 'Reis kochen (oder Reste vom Vortag nehmen).|Gemüse scharf anbraten, Reis dazugeben.|Mit Sojasoße und Pfeffer würzen, nach Wunsch ein Ei unterrühren.'],
    ['haehnchen-curry', 'Hähnchen-Curry', '🍛', 30, 'haupt', 'haehnchen kokosmilch reis', 'paprika zwiebeln spinat erbsen', 'Reis kochen.|Hähnchen und Zwiebel anbraten, Currypaste oder -pulver kurz mitrösten.|Gemüse und Kokosmilch dazu, 10 Min. köcheln, mit Reis servieren.'],
    ['risi-bisi', 'Risi e Bisi', '🫛', 30, 'haupt', 'reis erbsen', 'parmesan butter zwiebeln schinken', 'Zwiebel anschwitzen, Reis glasig dünsten.|Mit Brühe aufgießen und 18 Min. garen, Erbsen die letzten 5 Min. dazu.|Butter und Parmesan unterrühren.'],
    ['paella', 'Pfannen-Paella', '🥘', 45, 'haupt', 'reis haehnchen paprika', 'erbsen fisch zwiebeln knoblauch tomaten', 'Hähnchen, Zwiebel und Paprika anbraten, Reis und Paprikapulver (Kurkuma) kurz mitrösten.|Tomaten und Brühe dazu, ohne Rühren ca. 20 Min. garen.|Erbsen und Garnelen die letzten Minuten mitgaren.'],
    ['gefuellte-paprika', 'Gefüllte Paprika', '🫑', 60, 'haupt', 'paprika hackfleisch reis', 'passata kaese zwiebeln', 'Reis halb gar kochen, mit angebratenem Hack und Zwiebel mischen, würzen.|Paprika aushöhlen und füllen, in Tomatensoße setzen.|Zugedeckt bei 180 °C ca. 40 Min. garen, zum Schluss mit Käse überbacken.'],
    ['lachs-bowl', 'Lachs-Reis-Bowl', '🍣', 25, 'haupt', 'reis lachs gurke', 'avocado karotten mais', 'Reis kochen.|Lachs braten oder roh (Sushi-Qualität) würfeln und mit Sojasoße marinieren.|Mit Gurke, Avocado und Karotte auf dem Reis anrichten, Sesam darüber.'],
    ['tofu-reis', 'Knuspriger Tofu mit Reis', '🧆', 30, 'haupt', 'tofu reis', 'brokkoli paprika karotten', 'Tofu trocken tupfen, würfeln, in Speisestärke wenden und knusprig braten.|Gemüse kurz anbraten, mit Sojasoße und etwas Honig glasieren.|Tofu dazugeben, mit Reis servieren.'],
    ['kuerbisrisotto', 'Kürbisrisotto', '🎃', 40, 'haupt', 'reis kuerbis parmesan', 'zwiebeln butter', 'Zwiebel und Kürbiswürfel anschwitzen, Risottoreis glasig dünsten.|Nach und nach heiße Brühe angießen und rühren (ca. 20 Min.).|Butter und Parmesan unterziehen.'],

    // ---------- Kartoffeln ----------
    ['ofenkartoffeln', 'Ofenkartoffeln mit Kräuterquark', '🥔', 50, 'haupt', 'kartoffeln quark', 'knoblauch gurke zwiebeln', 'Große Kartoffeln waschen, längs halbieren, mit Öl und Salz bei 200 °C 40 Min. backen.|Quark mit Kräutern, Knoblauch, Salz und Pfeffer verrühren.|Kartoffeln mit Quark und Gurkenscheiben servieren.'],
    ['kartoffelpuffer', 'Kartoffelpuffer mit Apfelmus', '🥔', 40, 'haupt', 'kartoffeln eier mehl', 'zwiebeln aepfel', '1 kg Kartoffeln und eine Zwiebel reiben, gut ausdrücken.|Mit 2 Eiern, 2 EL Mehl und Salz mischen.|Flache Puffer in reichlich Öl knusprig braten, mit Apfelmus servieren.'],
    ['kartoffelsalat-wuerstchen', 'Kartoffelsalat mit Würstchen', '🌭', 40, 'haupt', 'kartoffeln wurst', 'gurke zwiebeln eier', 'Kartoffeln kochen, pellen und in Scheiben schneiden.|Mit warmer Brühe, Essig, Öl, Zwiebel und Gurke anmachen und ziehen lassen.|Mit Würstchen servieren.'],
    ['kartoffel-gemuese-pfanne', 'Kartoffel-Gemüse-Pfanne', '🥘', 35, 'haupt', 'kartoffeln paprika zucchini', 'zwiebeln champignons feta', 'Kartoffelwürfel 15 Min. braten.|Gemüse dazugeben und weitere 10 Min. braten.|Würzen, nach Wunsch mit Feta servieren.'],
    ['kartoffelgulasch', 'Kartoffelgulasch', '🍲', 40, 'haupt', 'kartoffeln wurst paprika', 'zwiebeln passata', 'Zwiebeln anschwitzen, Paprikapulver und Tomatenmark kurz mitrösten.|Kartoffelwürfel, Paprika und Brühe dazu, 20 Min. köcheln.|Würstchenscheiben darin erwärmen.'],
    ['gefuellte-suesskartoffel', 'Gefüllte Süßkartoffel', '🍠', 50, 'haupt', 'suesskartoffel bohnen', 'mais feta sauresahne avocado', 'Süßkartoffeln bei 200 °C ca. 45 Min. weich backen.|Bohnen und Mais mit Kreuzkümmel erwärmen.|Kartoffeln aufschneiden, füllen, mit Feta oder Schmand toppen.'],
    ['suesskartoffel-pommes', 'Süßkartoffel-Pommes mit Dip', '🍟', 35, 'snack', 'suesskartoffel joghurt', 'knoblauch', 'Süßkartoffeln in Stifte schneiden, mit etwas Stärke, Öl und Salz mischen.|Mit Abstand auf dem Blech bei 220 °C ca. 25 Min. backen, einmal wenden.|Joghurt mit Knoblauch und Salz als Dip.'],
    ['hack-kartoffel-auflauf', 'Hackfleisch-Kartoffel-Auflauf', '🥧', 60, 'haupt', 'hackfleisch kartoffeln karotten', 'erbsen zwiebeln milch kaese', 'Hack mit Zwiebel und Karotte anbraten, Erbsen und etwas Tomatenmark dazu.|Kartoffeln kochen und mit Milch und Butter zu Püree stampfen.|Hack in die Form, Püree darauf, mit Käse bei 200 °C 25 Min. backen.'],
    ['kartoffel-lauch-gratin', 'Kartoffel-Lauch-Gratin', '🥬', 55, 'haupt', 'kartoffeln lauch sahne', 'kaese speck', 'Kartoffeln in dünne Scheiben, Lauch in Ringe schneiden.|Abwechselnd in eine Form schichten, Sahne mit Salz, Pfeffer und Muskat darübergießen.|Mit Käse bestreuen und bei 180 °C ca. 45 Min. backen.'],
    ['kartoffelspalten', 'Kartoffelspalten mit Kräuterdip', '🥔', 40, 'snack', 'kartoffeln sauresahne', 'knoblauch', 'Kartoffeln in Spalten schneiden, mit Öl, Paprikapulver und Salz mischen.|Bei 220 °C ca. 30 Min. knusprig backen.|Schmand mit Kräutern und Knoblauch verrühren.'],
    ['tortilla-espanola', 'Spanische Tortilla', '🍳', 40, 'haupt', 'kartoffeln eier zwiebeln', 'paprika kaese', 'Kartoffeln und Zwiebeln in dünnen Scheiben in viel Öl langsam weich garen.|Abtropfen lassen und mit 6 verquirlten Eiern mischen.|In der Pfanne stocken lassen, mit einem Teller wenden, kurz fertig braten.'],
    ['spargel-klassisch', 'Spargel mit Kartoffeln und Schinken', '🌱', 40, 'haupt', 'spargel kartoffeln', 'schinken butter eier', 'Spargel schälen und in Salzwasser mit etwas Zucker 12–15 Min. garen.|Kartoffeln kochen.|Mit Schinken und zerlassener Butter (oder Hollandaise) servieren.'],

    // ---------- Fleisch ----------
    ['frikadellen', 'Frikadellen', '🍔', 30, 'haupt', 'hackfleisch eier brot', 'zwiebeln kartoffeln salat gurke', 'Altbackenes Brötchen einweichen und ausdrücken.|Mit Hack, Ei, Zwiebel, Senf, Salz und Pfeffer verkneten, flache Bällchen formen.|Von beiden Seiten je ca. 5 Min. braten.'],
    ['koenigsberger-klopse', 'Königsberger Klopse', '🍽️', 50, 'haupt', 'hackfleisch eier sahne', 'kartoffeln zitrone zwiebeln mehl butter', 'Hack mit Ei, eingeweichtem Brötchen und Zwiebel verkneten, Klopse formen.|In leicht köchelnder Brühe 15 Min. garziehen lassen.|Aus Butter, Mehl, Brühe und Sahne eine Soße kochen, mit Zitrone und Kapern abschmecken.'],
    ['hackbraten', 'Hackbraten', '🍖', 75, 'haupt', 'hackfleisch eier zwiebeln', 'brot kartoffeln karotten', 'Hack mit Ei, Zwiebel, eingeweichtem Brot und Gewürzen verkneten.|Zu einem Laib formen, mit Gemüse in eine Form legen.|Bei 180 °C ca. 60 Min. braten.'],
    ['ofen-haehnchen', 'Ofen-Hähnchen mit Gemüse', '🍗', 50, 'haupt', 'haehnchen kartoffeln paprika', 'zucchini zwiebeln knoblauch karotten', 'Kartoffeln und Gemüse in Stücke schneiden, mit Öl und Gewürzen aufs Blech.|Hähnchen würzen und dazulegen.|Bei 200 °C ca. 40 Min. backen, bis alles goldbraun ist.'],
    ['haehnchen-geschnetzeltes', 'Hähnchengeschnetzeltes in Rahmsoße', '🍗', 30, 'haupt', 'haehnchen champignons sahne', 'reis nudeln zwiebeln', 'Hähnchenstreifen scharf anbraten, herausnehmen.|Pilze und Zwiebel braten, mit Sahne und etwas Brühe ablöschen.|Fleisch zurückgeben, abschmecken, mit Reis oder Nudeln servieren.'],
    ['haehnchen-salat', 'Salat mit gebratenem Hähnchen', '🥗', 20, 'salat', 'salat haehnchen', 'tomaten gurke mais paprika feta', 'Hähnchenbrust würzen, braten und in Streifen schneiden.|Salat und Gemüse vorbereiten.|Mit Dressing anmachen, Hähnchen darauf verteilen.'],
    ['gyros-pfanne', 'Gyros-Pfanne mit Tzatziki', '🥙', 30, 'haupt', 'schwein zwiebeln joghurt', 'gurke knoblauch reis kartoffeln paprika', 'Schweinefleisch in Streifen mit Gyrosgewürz marinieren und mit Zwiebeln scharf braten.|Tzatziki: Joghurt, geriebene Gurke, Knoblauch, Salz.|Mit Reis oder Pommes servieren.'],
    ['zuercher-geschnetzeltes', 'Zürcher Geschnetzeltes', '🍽️', 30, 'haupt', 'schwein champignons sahne', 'zwiebeln kartoffeln reis', 'Fleisch in Streifen portionsweise scharf anbraten.|Zwiebel und Pilze braten, mit Sahne und Brühe ablöschen.|Fleisch darin erwärmen, mit Rösti, Reis oder Nudeln servieren.'],
    ['rouladen', 'Rinderrouladen', '🥩', 120, 'haupt', 'rind speck gurke', 'zwiebeln karotten kartoffeln', 'Rouladen mit Senf bestreichen, mit Speck, Zwiebel und Gurke belegen, aufrollen und feststecken.|Rundherum scharf anbraten, Gemüse mitrösten, mit Brühe (und Rotwein) ablöschen.|Zugedeckt ca. 90 Min. schmoren, Soße abbinden.'],
    ['steak-ofengemuese', 'Steak mit Kräuterbutter und Ofengemüse', '🥩', 45, 'haupt', 'rind kartoffeln', 'butter knoblauch paprika zucchini', 'Kartoffeln und Gemüse bei 200 °C ca. 35 Min. rösten.|Steak bei Zimmertemperatur sehr heiß 2–3 Min. pro Seite braten, 5 Min. ruhen lassen.|Mit Kräuterbutter servieren.'],
    ['currywurst', 'Currywurst mit Pommes', '🌭', 35, 'haupt', 'wurst passata kartoffeln', 'zwiebeln', 'Kartoffeln als Ofenpommes backen.|Zwiebel anschwitzen, Tomaten, Currypulver, etwas Zucker und Essig 10 Min. köcheln.|Würstchen braten, in Scheiben schneiden und mit Soße und Curry bestreuen.'],
    ['burger', 'Hausgemachte Burger', '🍔', 30, 'haupt', 'hackfleisch brot salat', 'tomaten kaese gurke zwiebeln', 'Hack mit Salz und Pfeffer zu flachen Patties formen.|Sehr heiß 3–4 Min. pro Seite braten, zum Schluss Käse darauf schmelzen.|Brötchen toasten und mit Salat, Tomate, Gurke und Soße belegen.'],
    ['burritos', 'Burritos', '🌯', 30, 'haupt', 'wraps hackfleisch bohnen', 'reis mais kaese sauresahne paprika tomaten', 'Hack mit Zwiebel, Kreuzkümmel und Paprikapulver anbraten, Bohnen und Mais dazu.|Wraps mit Reis, Füllung, Käse und Schmand belegen.|Einrollen und in der Pfanne kurz anrösten.'],
    ['kohlrouladen', 'Kohlrouladen', '🥬', 90, 'haupt', 'kohl hackfleisch', 'reis zwiebeln passata speck', 'Große Kohlblätter kurz blanchieren.|Mit gewürztem Hack (und Reis) füllen und aufrollen.|Anbraten, mit Brühe oder Tomatensoße ca. 60 Min. schmoren.'],
    ['schupfnudeln-kraut', 'Schupfnudeln mit Sauerkraut', '🥟', 25, 'haupt', 'gnocchi kohl speck', 'zwiebeln', 'Speck und Zwiebel anbraten.|Schupfnudeln dazugeben und goldbraun braten.|Sauerkraut untermischen und 5 Min. mitbraten.'],

    // ---------- Fisch ----------
    ['fisch-ofengemuese', 'Fisch auf Ofengemüse', '🐟', 40, 'haupt', 'fisch kartoffeln tomaten', 'zucchini zitrone knoblauch', 'Kartoffelscheiben 20 Min. bei 200 °C vorbacken.|Gemüse und Fischfilet darauflegen, mit Zitrone, Öl und Kräutern würzen.|Weitere 15 Min. backen.'],
    ['lachs-spinat', 'Lachs auf Blattspinat mit Reis', '🐟', 30, 'haupt', 'lachs spinat reis', 'sahne knoblauch zitrone', 'Reis kochen.|Lachs auf der Hautseite knusprig braten.|Spinat mit Knoblauch (und Sahne) zusammenfallen lassen, mit Muskat würzen, alles anrichten.'],
    ['fisch-pueree', 'Fischstäbchen mit Kartoffelpüree', '🐠', 30, 'haupt', 'fisch kartoffeln milch', 'butter erbsen spinat', 'Kartoffeln kochen und mit warmer Milch, Butter und Muskat stampfen.|Fischstäbchen in der Pfanne oder im Ofen knusprig backen.|Mit Erbsen oder Spinat servieren.'],
    ['thunfischsalat', 'Thunfischsalat', '🥗', 15, 'salat', 'thunfisch mais salat', 'tomaten gurke eier zwiebeln bohnen', 'Salat und Gemüse waschen und schneiden.|Thunfisch abtropfen lassen, mit Mais darüber verteilen.|Mit Essig-Öl-Dressing anmachen, mit Ei toppen.'],
    ['thunfisch-wraps', 'Thunfisch-Wraps', '🌯', 15, 'snack', 'wraps thunfisch', 'mais salat frischkaese gurke', 'Thunfisch mit Frischkäse, Mais, Salz und Pfeffer verrühren.|Wraps damit bestreichen, mit Salat und Gurke belegen.|Fest einrollen und halbieren.'],
    ['fischcurry', 'Fisch-Curry', '🍛', 30, 'haupt', 'fisch kokosmilch', 'reis spinat paprika tomaten', 'Zwiebel, Knoblauch und Currypaste anschwitzen, Kokosmilch und Gemüse dazu.|5 Min. köcheln, Fisch in Stücken dazugeben.|Bei kleiner Hitze 5–7 Min. garziehen lassen, mit Reis servieren.'],

    // ---------- Vegetarisch ----------
    ['falafel', 'Falafel mit Joghurtsoße', '🧆', 45, 'haupt', 'kichererbsen zwiebeln', 'knoblauch mehl joghurt salat tomaten wraps', 'Kichererbsen abtropfen, mit Zwiebel, Knoblauch, Kräutern, Kreuzkümmel und 2 EL Mehl fein hacken.|Bällchen formen und in Öl braten oder bei 200 °C 20 Min. backen.|Mit Joghurtsoße, Salat und Fladenbrot servieren.'],
    ['kichererbsen-curry', 'Kichererbsen-Spinat-Curry', '🍛', 25, 'haupt', 'kichererbsen spinat kokosmilch', 'reis zwiebeln tomaten', 'Zwiebel, Knoblauch und Currypulver anschwitzen.|Kichererbsen, Tomaten und Kokosmilch dazu, 10 Min. köcheln.|Spinat unterrühren, mit Reis servieren.'],
    ['dal', 'Linsen-Dal', '🥣', 30, 'haupt', 'linsen kokosmilch', 'passata zwiebeln reis spinat knoblauch', 'Zwiebel, Knoblauch, Ingwer und Gewürze (Kurkuma, Kreuzkümmel) anschwitzen.|Rote Linsen, Tomaten und Wasser dazu, 15 Min. köcheln.|Kokosmilch einrühren, mit Reis oder Brot servieren.'],
    ['auberginen-auflauf', 'Auberginen-Auflauf (Parmigiana)', '🍆', 60, 'haupt', 'aubergine passata mozzarella', 'parmesan knoblauch', 'Auberginen in Scheiben salzen, abtupfen und anbraten oder im Ofen backen.|Mit Tomatensoße und Mozzarella schichten, Parmesan darüber.|Bei 200 °C ca. 30 Min. backen.'],
    ['ratatouille', 'Ratatouille', '🍆', 45, 'haupt', 'zucchini aubergine paprika', 'tomaten zwiebeln knoblauch reis brot', 'Gemüse würfeln, Zwiebel und Knoblauch anschwitzen.|Aubergine und Paprika braten, Zucchini und Tomaten dazu.|Mit Kräutern der Provence 20 Min. schmoren, zu Reis oder Baguette.'],
    ['tofu-gemuese-pfanne', 'Tofu-Gemüse-Pfanne', '🥦', 25, 'haupt', 'tofu brokkoli paprika', 'karotten reis nudeln', 'Tofu würfeln und knusprig braten, herausnehmen.|Gemüse im Wok scharf anbraten.|Tofu zurückgeben, mit Sojasoße, Knoblauch und etwas Honig würzen.'],
    ['quiche', 'Gemüse-Quiche', '🥧', 75, 'haupt', 'mehl butter eier sahne', 'lauch speck kaese brokkoli spinat', 'Mürbeteig aus 200 g Mehl, 100 g Butter, 1 Ei und Salz kneten, 30 Min. kühlen.|In eine Form drücken, mit Gemüse belegen.|3 Eier mit 200 ml Sahne und Käse darübergießen, bei 180 °C 40 Min. backen.'],
    ['flammkuchen', 'Flammkuchen', '🔥', 40, 'haupt', 'mehl sauresahne zwiebeln', 'speck kaese', 'Teig aus 250 g Mehl, 125 ml Wasser, 2 EL Öl und Salz dünn ausrollen.|Mit Schmand bestreichen, mit Zwiebelringen und Speck belegen.|Bei maximaler Hitze 10–12 Min. knusprig backen.'],
    ['pizza-blech', 'Pizza vom Blech', '🍕', 60, 'haupt', 'mehl passata mozzarella', 'schinken paprika champignons mais zwiebeln wurst', 'Teig aus 500 g Mehl, Hefe, 300 ml Wasser, Öl und Salz kneten, 30 Min. gehen lassen.|Aufs Blech ausrollen, mit gewürzter Tomatensoße bestreichen und belegen.|Bei 230 °C ca. 15 Min. backen.'],
    ['gefuellte-zucchini', 'Gefüllte Zucchini', '🥒', 50, 'haupt', 'zucchini hackfleisch', 'reis kaese passata feta', 'Zucchini längs halbieren und aushöhlen.|Fruchtfleisch mit Hack (oder Feta für vegetarisch) anbraten und würzen.|Füllen, mit Käse bestreuen und bei 200 °C 25 Min. backen.'],
    ['gefuellte-champignons', 'Gefüllte Champignons', '🍄', 30, 'snack', 'champignons frischkaese', 'schinken knoblauch kaese', 'Stiele aus großen Champignons drehen und fein hacken.|Mit Frischkäse, Knoblauch (und Schinken) mischen.|Pilze füllen, mit Käse bestreuen, bei 200 °C 15 Min. backen.'],
    ['blumenkohl-ofen', 'Gerösteter Blumenkohl mit Joghurt', '🥦', 40, 'haupt', 'blumenkohl joghurt', 'kichererbsen zitrone knoblauch', 'Blumenkohl in Röschen mit Öl, Kreuzkümmel und Paprika mischen.|Bei 220 °C ca. 25 Min. rösten (Kichererbsen mitrösten).|Mit Knoblauch-Zitronen-Joghurt servieren.'],
    ['herzhafte-pfannkuchen', 'Herzhafte Pfannkuchen mit Spinat & Feta', '🥞', 35, 'haupt', 'mehl eier milch spinat', 'feta kaese schinken', 'Pfannkuchenteig rühren und dünne Pfannkuchen backen.|Spinat mit Knoblauch dünsten, Feta zerbröseln.|Pfannkuchen füllen, einrollen und kurz im Ofen überbacken.'],
    ['gemuese-wraps', 'Gemüse-Wraps mit Hummus', '🌯', 20, 'snack', 'wraps kichererbsen', 'paprika gurke karotten salat', 'Kichererbsen mit Zitrone, Knoblauch und Öl zu Hummus pürieren.|Wraps bestreichen, mit Gemüsestreifen belegen.|Fest einrollen.'],
    ['ofenspargel', 'Ofenspargel mit Parmesan', '🌱', 30, 'haupt', 'spargel parmesan', 'kartoffeln zitrone schinken', 'Grünen Spargel (unteres Drittel schälen) mit Öl, Salz und Pfeffer aufs Blech.|Bei 200 °C ca. 15 Min. rösten, Parmesan darüber.|Mit Zitrone, nach Wunsch mit Schinken und Kartoffeln servieren.'],
    ['ofenkuerbis', 'Ofenkürbis mit Feta', '🎃', 40, 'haupt', 'kuerbis feta', 'zwiebeln kichererbsen spinat', 'Hokkaido in Spalten schneiden, mit Öl, Salz und Rosmarin mischen.|Bei 200 °C ca. 30 Min. rösten.|Feta darüberbröseln, mit Honig beträufeln.'],
    ['buddha-bowl', 'Buddha-Bowl', '🥗', 30, 'haupt', 'reis kichererbsen avocado', 'karotten gurke spinat joghurt mais', 'Reis kochen, Kichererbsen mit Gewürzen rösten.|Gemüse schneiden, Avocado in Scheiben.|Alles nebeneinander in einer Schüssel anrichten, mit Joghurt- oder Erdnusssoße.'],
    ['linsensalat', 'Linsensalat mit Feta', '🥗', 30, 'salat', 'linsen feta paprika', 'gurke zwiebeln zitrone', 'Linsen bissfest kochen und abkühlen lassen.|Mit Paprika, Gurke und Zwiebel mischen.|Mit Zitrone, Öl, Salz anmachen, Feta darüber.'],

    // ---------- Suppen & Eintöpfe ----------
    ['tomatensuppe', 'Tomatensuppe', '🍅', 25, 'suppe', 'passata zwiebeln', 'sahne knoblauch brot tomaten', 'Zwiebel und Knoblauch anschwitzen, Tomaten und etwas Brühe dazu.|15 Min. köcheln, pürieren, mit Salz, Zucker und Basilikum abschmecken.|Mit einem Klecks Sahne und Brot servieren.'],
    ['kartoffel-lauch-suppe', 'Kartoffel-Lauch-Suppe', '🥬', 35, 'suppe', 'kartoffeln lauch', 'sahne speck wurst', 'Lauch und Kartoffeln klein schneiden und anschwitzen.|Mit Brühe bedecken, 20 Min. kochen.|Teilweise pürieren, mit Sahne und Muskat abschmecken.'],
    ['moehrensuppe', 'Möhren-Ingwer-Suppe', '🥕', 30, 'suppe', 'karotten kokosmilch', 'zwiebeln kartoffeln zitrone', 'Möhren, Zwiebel und Ingwer anschwitzen.|Mit Brühe 20 Min. weich kochen.|Mit Kokosmilch pürieren, mit Zitrone abschmecken.'],
    ['champignonsuppe', 'Champignoncremesuppe', '🍄', 30, 'suppe', 'champignons sahne', 'zwiebeln kartoffeln', 'Pilze und Zwiebel anbraten (ein paar Scheiben für die Deko beiseite).|Mit Brühe 15 Min. köcheln.|Mit Sahne pürieren und würzen.'],
    ['erbsensuppe', 'Erbsensuppe', '🫛', 40, 'suppe', 'erbsen kartoffeln', 'wurst speck karotten lauch zwiebeln', 'Zwiebel, Speck und Gemüse anschwitzen.|Erbsen, Kartoffeln und Brühe dazu, 25 Min. köcheln.|Teilweise pürieren, Würstchen darin erwärmen.'],
    ['huehnersuppe', 'Hühnersuppe', '🍜', 60, 'suppe', 'haehnchen karotten nudeln', 'lauch zwiebeln', 'Hähnchen mit Suppengemüse in Wasser 45 Min. leise köcheln.|Fleisch herauslösen und klein zupfen.|Suppennudeln in der Brühe garen, Fleisch zurückgeben, würzen.'],
    ['gulaschsuppe', 'Gulaschsuppe', '🍲', 90, 'suppe', 'rind paprika kartoffeln', 'zwiebeln passata', 'Fleischwürfel scharf anbraten, viele Zwiebeln dazu, Paprikapulver und Tomatenmark mitrösten.|Mit Brühe 60 Min. köcheln.|Kartoffeln und Paprika dazu, weitere 20 Min. garen.'],
    ['minestrone', 'Minestrone', '🥣', 40, 'suppe', 'zucchini karotten bohnen', 'nudeln tomaten lauch parmesan passata', 'Gemüse würfeln und anschwitzen.|Tomaten und Brühe dazu, 15 Min. köcheln.|Bohnen und Suppennudeln mitgaren, mit Parmesan servieren.'],
    ['zucchinisuppe', 'Zucchini-Cremesuppe', '🥒', 25, 'suppe', 'zucchini kartoffeln', 'frischkaese zwiebeln', 'Zwiebel, Zucchini und Kartoffel anschwitzen.|Mit Brühe 15 Min. kochen.|Mit Frischkäse pürieren und abschmecken.'],
    ['blumenkohlsuppe', 'Blumenkohlsuppe', '🥦', 30, 'suppe', 'blumenkohl kartoffeln', 'sahne kaese zwiebeln', 'Blumenkohl und Kartoffeln mit Zwiebel in Brühe 20 Min. kochen.|Pürieren, mit Sahne und Muskat abschmecken.|Mit geriebenem Käse servieren.'],
    ['kaese-lauch-suppe', 'Käse-Lauch-Suppe', '🧀', 35, 'suppe', 'hackfleisch lauch frischkaese', 'zwiebeln champignons brot', 'Hack krümelig braten, Lauch in Ringen dazugeben.|Mit Brühe 15 Min. köcheln.|Schmelzkäse oder Frischkäse einrühren, bis er geschmolzen ist.'],
    ['linseneintopf', 'Linseneintopf mit Würstchen', '🌭', 45, 'suppe', 'linsen wurst karotten', 'kartoffeln lauch speck zwiebeln', 'Speck, Zwiebel und Gemüse anschwitzen.|Linsen und Brühe dazu, 30 Min. köcheln.|Mit Essig und Pfeffer abschmecken, Würstchen darin erwärmen.'],
    ['bohneneintopf', 'Bohneneintopf', '🫘', 45, 'suppe', 'bohnen kartoffeln', 'speck wurst karotten zwiebeln passata', 'Speck und Zwiebel anbraten.|Kartoffeln, Gemüse und Brühe dazu, 20 Min. kochen.|Bohnen dazugeben, mit Bohnenkraut würzen.'],
    ['wirsingeintopf', 'Wirsing-Kartoffel-Eintopf', '🥬', 45, 'suppe', 'kohl kartoffeln', 'wurst karotten zwiebeln speck', 'Zwiebel und Speck anschwitzen.|Wirsing in Streifen, Kartoffeln und Karotten dazu, mit Brühe bedecken.|25 Min. köcheln, mit Muskat und Kümmel würzen.'],

    // ---------- Salate ----------
    ['gurkensalat', 'Gurkensalat', '🥒', 10, 'salat', 'gurke joghurt', 'zwiebeln sauresahne', 'Gurke in feine Scheiben hobeln, leicht salzen.|Joghurt mit Dill, Salz, Pfeffer und etwas Zucker verrühren.|Mischen und kurz ziehen lassen.'],
    ['caesar-salad', 'Caesar Salad', '🥗', 25, 'salat', 'salat haehnchen parmesan', 'brot knoblauch zitrone', 'Brotwürfel mit Knoblauch in Öl rösten.|Hähnchen braten und in Streifen schneiden.|Romanasalat mit Dressing aus Joghurt/Mayo, Zitrone, Senf und Parmesan mischen.'],
    ['bohnensalat', 'Bunter Bohnensalat', '🫘', 15, 'salat', 'bohnen mais paprika', 'zwiebeln tomaten', 'Bohnen und Mais abspülen.|Mit gewürfelter Paprika und Zwiebel mischen.|Mit Essig, Öl, Salz und Pfeffer anmachen.'],
    ['kartoffelsalat', 'Kartoffelsalat mit Brühe', '🥔', 40, 'salat', 'kartoffeln zwiebeln', 'gurke speck', 'Festkochende Kartoffeln kochen, noch warm pellen und schneiden.|Mit heißer Brühe, Essig, Senf und Öl übergießen.|Zwiebelwürfel untermischen, mind. 30 Min. ziehen lassen.'],
    ['reissalat', 'Reissalat', '🍚', 30, 'salat', 'reis mais erbsen', 'paprika schinken joghurt gurke', 'Reis kochen und abkühlen lassen.|Mit Gemüse und Schinkenwürfeln mischen.|Mit Joghurt-Dressing oder Essig und Öl anmachen.'],
    ['rohkost', 'Apfel-Möhren-Rohkost', '🥕', 10, 'salat', 'karotten aepfel', 'zitrone', 'Möhren und Apfel grob reiben.|Mit Zitronensaft, etwas Öl und einer Prise Zucker mischen.|Nach Wunsch Nüsse darüberstreuen.'],
    ['avocado-tomaten-salat', 'Tomaten-Avocado-Salat', '🥑', 10, 'salat', 'tomaten avocado', 'zwiebeln mozzarella zitrone', 'Tomaten und Avocado würfeln.|Mit Zwiebel und Mozzarella mischen.|Mit Zitrone, Olivenöl, Salz und Pfeffer anmachen.'],
    ['krautsalat', 'Krautsalat', '🥬', 20, 'salat', 'kohl karotten', 'aepfel zwiebeln speck', 'Weißkohl fein hobeln, mit Salz kräftig durchkneten.|Möhre (und Apfel) dazureiben.|Mit Essig, Öl, Zucker und Kümmel anmachen, ziehen lassen.'],

    // ---------- Snacks & Brot ----------
    ['bruschetta', 'Bruschetta', '🍅', 15, 'snack', 'brot tomaten', 'knoblauch mozzarella', 'Brotscheiben rösten und mit Knoblauch einreiben.|Tomaten würfeln, mit Olivenöl, Salz und Basilikum mischen.|Auf das Brot geben.'],
    ['wrap-roellchen', 'Wrap-Röllchen', '🌯', 15, 'snack', 'wraps frischkaese schinken', 'salat gurke', 'Wraps mit Frischkäse bestreichen.|Mit Schinken und Salat belegen, fest aufrollen.|In Scheiben schneiden.'],
    ['club-sandwich', 'Club-Sandwich', '🥪', 20, 'snack', 'brot haehnchen speck salat', 'tomaten eier', 'Toast rösten, Speck knusprig braten, Hähnchen braten.|Toast mit Mayo bestreichen und mit Salat, Tomate, Hähnchen und Speck schichten.|Diagonal halbieren.'],
    ['gefuellte-eier', 'Gefüllte Eier', '🥚', 20, 'snack', 'eier frischkaese', 'sauresahne schinken', 'Eier hart kochen, halbieren, Eigelb herauslösen.|Eigelb mit Frischkäse, Senf, Salz und Paprika verrühren.|In die Eiweißhälften spritzen.'],
    ['knoblauchbrot', 'Knoblauchbrot', '🧄', 15, 'snack', 'brot butter knoblauch', 'kaese', 'Weiche Butter mit Knoblauch, Kräutern und Salz verrühren.|Baguette einschneiden und füllen.|Bei 200 °C ca. 10 Min. backen.'],
    ['tzatziki', 'Tzatziki', '🥒', 10, 'snack', 'joghurt gurke knoblauch', '', 'Gurke raspeln, salzen und ausdrücken.|Mit griechischem Joghurt und Knoblauch verrühren.|Mit Olivenöl und Salz abschmecken.'],
    ['guacamole', 'Guacamole', '🥑', 10, 'snack', 'avocado zitrone', 'tomaten zwiebeln knoblauch', 'Avocado mit der Gabel zerdrücken.|Mit Limette, Salz und fein gehackter Zwiebel/Tomate mischen.|Sofort servieren (Kern hineinlegen hält sie grün).'],
    ['hummus', 'Hummus mit Gemüsesticks', '🫘', 15, 'snack', 'kichererbsen zitrone', 'knoblauch karotten gurke paprika brot', 'Kichererbsen mit Zitrone, Knoblauch, Tahin (oder Öl) und etwas Wasser cremig pürieren.|Mit Salz und Kreuzkümmel abschmecken.|Mit Gemüsesticks und Brot servieren.'],

    // ---------- Süßes & Backen ----------
    ['apfel-crumble', 'Apfel-Crumble', '🍏', 45, 'suess', 'aepfel mehl butter', 'haferflocken beeren', 'Äpfel würfeln, mit Zimt und etwas Zucker in eine Form geben.|Je 100 g Mehl, Butter und Zucker (gern mit Haferflocken) zu Streuseln verkneten.|Darüber verteilen, bei 180 °C ca. 30 Min. backen.'],
    ['bananen-muffins', 'Bananen-Muffins', '🧁', 35, 'suess', 'bananen mehl eier', 'schokolade haferflocken butter', '2 reife Bananen zerdrücken, mit 1 Ei, 80 ml Öl und 80 g Zucker verrühren.|200 g Mehl mit 2 TL Backpulver unterheben, Schokostücke dazu.|In Muffinförmchen bei 180 °C ca. 22 Min. backen.'],
    ['schoko-muffins', 'Schokomuffins', '🧁', 35, 'suess', 'mehl eier schokolade butter', 'milch bananen', 'Butter und Schokolade schmelzen, mit 2 Eiern, Zucker und Milch verrühren.|Mehl mit Backpulver und Kakao unterheben.|Bei 180 °C ca. 20 Min. backen.'],
    ['kaesekuchen', 'Käsekuchen ohne Boden', '🍰', 75, 'suess', 'quark eier', 'zitrone butter beeren', '1 kg Quark, 4 Eier, 150 g Zucker, 1 Pck. Puddingpulver und Zitronenabrieb verrühren.|In eine gefettete Springform füllen.|Bei 170 °C ca. 60 Min. backen, im Ofen auskühlen lassen.'],
    ['waffeln', 'Waffeln', '🧇', 30, 'suess', 'mehl eier milch butter', 'beeren schokolade', '125 g Butter mit 80 g Zucker und 3 Eiern schaumig rühren.|250 g Mehl, 1 TL Backpulver und 250 ml Milch einrühren.|Im Waffeleisen goldbraun backen.'],
    ['beeren-schichtdessert', 'Beeren-Quark-Schichtdessert', '🍓', 20, 'suess', 'quark beeren', 'sahne zitrone joghurt', 'Quark mit Joghurt, Zucker und Zitrone glatt rühren, geschlagene Sahne unterheben.|Abwechselnd mit Beeren in Gläser schichten.|Kühl stellen.'],
    ['milchshake', 'Erdbeer-Milchshake', '🥤', 5, 'suess', 'beeren milch', 'joghurt bananen', 'Beeren mit kalter Milch (und einer Banane) in den Mixer geben.|Fein pürieren, nach Geschmack süßen.|Sofort trinken.'],
    ['bratapfel', 'Bratäpfel', '🍎', 35, 'suess', 'aepfel', 'haferflocken butter quark', 'Kerngehäuse ausstechen.|Mit Haferflocken, Zimt, Butter und Honig (oder Rosinen/Nüssen) füllen.|Bei 180 °C ca. 25 Min. backen, mit Vanillesoße oder Quark servieren.'],
    ['mousse-au-chocolat', 'Mousse au Chocolat', '🍫', 20, 'suess', 'schokolade sahne', 'eier', '150 g Zartbitterschokolade schmelzen und etwas abkühlen lassen.|200 ml Sahne steif schlagen und unter die Schokolade heben.|Mind. 2 Std. kühlen.'],
    ['zitronenkuchen', 'Zitronenkuchen', '🍋', 70, 'suess', 'mehl eier butter zitrone', '', '200 g Butter, 200 g Zucker und 4 Eier schaumig rühren, Zitronenabrieb dazu.|250 g Mehl mit Backpulver unterheben.|In einer Kastenform bei 175 °C ca. 50 Min. backen, mit Zitronenguss bestreichen.'],
    ['nicecream', 'Bananen-Eis (Nicecream)', '🍨', 5, 'suess', 'bananen', 'beeren schokolade', 'Reife Bananen in Scheiben schneiden und einfrieren.|Gefroren im Mixer cremig pürieren.|Sofort mit Beeren oder Schokostückchen servieren.'],
    ['energy-balls', 'Haferflocken-Energiebällchen', '⚡', 15, 'suess', 'haferflocken bananen', 'schokolade', 'Reife Banane zerdrücken und mit Haferflocken zu einer formbaren Masse mischen.|Schokostückchen oder Nüsse unterkneten.|Kugeln formen und kühl stellen.'],
  ].map(([id, name, emoji, minutes, cat, ing, opt, steps]) => ({
    id, name, emoji, minutes, cat,
    ingredients: ing.split(' ').filter(Boolean),
    optional: opt.split(' ').filter(Boolean),
    steps: steps.split('|'),
  }));

  return BASE.map((r) => ({ cat: BASE_CAT[r.id] || 'haupt', ...r })).concat(MORE);
});
