/* Rezeptsammlung. Salz, Pfeffer, Öl, Zucker und Gewürze werden als Grundvorrat vorausgesetzt.
   ingredients = nötig, optional = passt gut dazu. Schlüssel siehe INGREDIENTS in logic.js. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.FridgeRecipes = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return [
    { id: 'ruehrei', name: 'Rührei mit Brot', emoji: '🍳', minutes: 10,
      ingredients: ['eier', 'brot'], optional: ['milch', 'schinken', 'tomaten', 'kaese', 'speck'],
      steps: ['Eier mit einem Schuss Milch, Salz und Pfeffer verquirlen.', 'In Butter oder Öl bei mittlerer Hitze langsam stocken lassen, dabei rühren.', 'Nach Belieben Schinken, Tomaten oder Käse unterheben und mit Brot servieren.'] },
    { id: 'omelett', name: 'Gemüse-Omelett', emoji: '🍳', minutes: 15,
      ingredients: ['eier', 'paprika'], optional: ['zwiebeln', 'champignons', 'spinat', 'kaese', 'tomaten', 'zucchini'],
      steps: ['Gemüse klein schneiden und in der Pfanne 3–4 Minuten anbraten.', 'Eier verquirlen, würzen und über das Gemüse gießen.', 'Bei kleiner Hitze mit Deckel stocken lassen, ggf. Käse darüberstreuen.'] },
    { id: 'pfannkuchen', name: 'Pfannkuchen', emoji: '🥞', minutes: 25,
      ingredients: ['mehl', 'eier', 'milch'], optional: ['aepfel', 'bananen', 'beeren', 'schokolade'],
      steps: ['250 g Mehl, 3 Eier, 500 ml Milch und eine Prise Salz glatt rühren, 10 Min. quellen lassen.', 'Dünn in einer gefetteten Pfanne von beiden Seiten goldbraun backen.', 'Mit Obst, Zucker & Zimt oder Schokolade servieren.'] },
    { id: 'french-toast', name: 'Arme Ritter (French Toast)', emoji: '🍞', minutes: 15,
      ingredients: ['brot', 'eier', 'milch'], optional: ['beeren', 'bananen', 'aepfel'],
      steps: ['Eier mit Milch, etwas Zucker und Zimt verquirlen.', 'Altbackenes Brot darin einweichen.', 'In Butter goldbraun braten, mit Obst servieren.'] },
    { id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', emoji: '🍝', minutes: 40,
      ingredients: ['nudeln', 'hackfleisch', 'passata'], optional: ['zwiebeln', 'knoblauch', 'karotten', 'parmesan'],
      steps: ['Zwiebel, Knoblauch und Karotte fein würfeln und anschwitzen.', 'Hackfleisch krümelig braten, Tomaten zugeben, 20 Min. köcheln, würzen.', 'Nudeln kochen und mit Soße und Parmesan servieren.'] },
    { id: 'pasta-tomate', name: 'Pasta mit Tomatensoße', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'passata'], optional: ['zwiebeln', 'knoblauch', 'mozzarella', 'parmesan', 'tomaten'],
      steps: ['Zwiebel und Knoblauch in Olivenöl anschwitzen.', 'Tomaten zugeben, mit Salz, Pfeffer, Zucker und Oregano 10 Min. köcheln.', 'Mit den gekochten Nudeln mischen, Käse darüber.'] },
    { id: 'carbonara', name: 'Spaghetti Carbonara', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'eier', 'speck', 'parmesan'], optional: ['sahne'],
      steps: ['Nudeln kochen. Speck knusprig braten.', 'Eigelb mit geriebenem Parmesan und Pfeffer verrühren.', 'Heiße Nudeln mit Speck mischen, Topf vom Herd, Eimasse und etwas Nudelwasser unterrühren.'] },
    { id: 'pasta-sahne-schinken', name: 'Nudeln in Schinken-Sahne-Soße', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'sahne', 'schinken'], optional: ['erbsen', 'champignons', 'kaese', 'zwiebeln'],
      steps: ['Zwiebel und Schinken in Würfeln anbraten.', 'Sahne zugießen, aufkochen, mit Salz, Pfeffer und Muskat würzen.', 'Erbsen/Pilze kurz mitgaren und mit den Nudeln vermengen.'] },
    { id: 'pasta-spinat', name: 'Pasta mit Spinat und Feta', emoji: '🍝', minutes: 20,
      ingredients: ['nudeln', 'spinat', 'feta'], optional: ['knoblauch', 'tomaten', 'sahne'],
      steps: ['Nudeln kochen.', 'Knoblauch anschwitzen, Spinat zusammenfallen lassen.', 'Feta zerbröseln, mit Nudeln und etwas Nudelwasser mischen.'] },
    { id: 'pesto-pasta', name: 'Pesto-Pasta', emoji: '🌿', minutes: 15,
      ingredients: ['nudeln', 'pesto'], optional: ['tomaten', 'parmesan', 'mozzarella', 'haehnchen'],
      steps: ['Nudeln kochen, etwas Nudelwasser aufheben.', 'Mit Pesto und einem Schluck Nudelwasser vermengen.', 'Mit Tomaten und Parmesan servieren.'] },
    { id: 'lasagne', name: 'Gemüse-Lasagne', emoji: '🧀', minutes: 60,
      ingredients: ['nudeln', 'zucchini', 'passata', 'kaese'], optional: ['paprika', 'spinat', 'milch', 'zwiebeln'],
      steps: ['Gemüse würfeln, anbraten, Tomaten zugeben und würzen.', 'Abwechselnd Lasagneplatten, Gemüsesoße und Käse schichten.', 'Bei 180 °C ca. 35 Min. backen.'] },
    { id: 'gnocchi-pfanne', name: 'Gnocchi-Pfanne mit Tomate & Mozzarella', emoji: '🥟', minutes: 20,
      ingredients: ['gnocchi', 'tomaten'], optional: ['mozzarella', 'spinat', 'zucchini', 'pesto', 'knoblauch'],
      steps: ['Gnocchi in Öl goldbraun braten.', 'Tomaten und Gemüse zugeben, kurz mitbraten, würzen.', 'Mozzarella darauf zerpflücken und mit Deckel schmelzen lassen.'] },
    { id: 'gebratener-reis', name: 'Gebratener Reis', emoji: '🍚', minutes: 20,
      ingredients: ['reis', 'eier'], optional: ['erbsen', 'karotten', 'paprika', 'schinken', 'haehnchen', 'lauch', 'mais'],
      steps: ['Am besten Reis vom Vortag verwenden.', 'Gemüse in heißem Öl scharf anbraten, Reis zugeben.', 'Eier unterrühren, mit Sojasoße abschmecken.'] },
    { id: 'curry', name: 'Gemüse-Curry mit Kokosmilch', emoji: '🍛', minutes: 30,
      ingredients: ['kokosmilch', 'reis'], optional: ['haehnchen', 'paprika', 'zucchini', 'brokkoli', 'karotten', 'kichererbsen', 'tofu', 'spinat', 'kuerbis', 'blumenkohl'],
      steps: ['Zwiebel, Knoblauch und Currypaste/-pulver anschwitzen.', 'Gemüse (und ggf. Fleisch/Tofu) zugeben, mit Kokosmilch ablöschen.', '15 Min. köcheln lassen, mit Reis servieren.'] },
    { id: 'haehnchen-gemuese', name: 'Hähnchen-Gemüse-Pfanne', emoji: '🍗', minutes: 25,
      ingredients: ['haehnchen', 'paprika'], optional: ['zucchini', 'brokkoli', 'reis', 'zwiebeln', 'champignons', 'karotten'],
      steps: ['Hähnchen in Streifen schneiden und scharf anbraten, herausnehmen.', 'Gemüse in der gleichen Pfanne braten.', 'Fleisch zurückgeben, würzen, mit Reis servieren.'] },
    { id: 'risotto', name: 'Pilzrisotto', emoji: '🍄', minutes: 35,
      ingredients: ['reis', 'champignons', 'parmesan'], optional: ['zwiebeln', 'butter', 'spinat'],
      steps: ['Zwiebel anschwitzen, Reis glasig dünsten.', 'Nach und nach heiße Brühe angießen und rühren, bis der Reis cremig ist (ca. 20 Min.).', 'Gebratene Pilze, Butter und Parmesan unterziehen.'] },
    { id: 'chili', name: 'Chili con Carne', emoji: '🌶️', minutes: 45,
      ingredients: ['hackfleisch', 'bohnen', 'passata'], optional: ['mais', 'paprika', 'zwiebeln', 'reis', 'brot'],
      steps: ['Hack mit Zwiebeln krümelig braten, mit Kreuzkümmel und Chili würzen.', 'Tomaten, Bohnen, Mais und Paprika zugeben.', '30 Min. köcheln, mit Reis oder Brot servieren.'] },
    { id: 'chili-sin-carne', name: 'Chili sin Carne', emoji: '🌶️', minutes: 35,
      ingredients: ['bohnen', 'passata', 'mais'], optional: ['linsen', 'paprika', 'zwiebeln', 'reis', 'karotten'],
      steps: ['Zwiebeln, Paprika und Karotten anbraten.', 'Tomaten, Bohnen, Mais (und rote Linsen) zugeben, kräftig würzen.', '20 Min. köcheln lassen.'] },
    { id: 'wraps', name: 'Gefüllte Wraps', emoji: '🌯', minutes: 20,
      ingredients: ['wraps', 'salat'], optional: ['haehnchen', 'tomaten', 'gurke', 'kaese', 'mais', 'paprika', 'bohnen', 'feta', 'frischkaese'],
      steps: ['Füllung vorbereiten: Fleisch braten, Gemüse schneiden.', 'Wraps kurz in der Pfanne erwärmen und mit Frischkäse oder Joghurtsoße bestreichen.', 'Füllen, einrollen, halbieren.'] },
    { id: 'quesadillas', name: 'Quesadillas', emoji: '🌮', minutes: 15,
      ingredients: ['wraps', 'kaese'], optional: ['mais', 'bohnen', 'paprika', 'haehnchen', 'zwiebeln'],
      steps: ['Eine Hälfte des Wraps mit Käse und Füllung belegen.', 'Zusammenklappen und in der Pfanne ohne Fett von beiden Seiten knusprig braten.', 'In Stücke schneiden.'] },
    { id: 'bratkartoffeln', name: 'Bratkartoffeln mit Spiegelei', emoji: '🥔', minutes: 30,
      ingredients: ['kartoffeln', 'eier'], optional: ['zwiebeln', 'speck', 'gurke'],
      steps: ['Gekochte Kartoffeln in Scheiben schneiden.', 'Mit Zwiebeln und Speck in Öl knusprig braten.', 'Spiegeleier dazu braten.'] },
    { id: 'kartoffelsuppe', name: 'Kartoffelsuppe', emoji: '🍲', minutes: 40,
      ingredients: ['kartoffeln', 'karotten'], optional: ['lauch', 'wurst', 'sahne', 'zwiebeln', 'speck'],
      steps: ['Kartoffeln, Karotten und Lauch würfeln, in Brühe 20 Min. kochen.', 'Teilweise pürieren, mit Sahne, Majoran und Muskat abschmecken.', 'Würstchen in Scheiben darin erwärmen.'] },
    { id: 'kartoffelgratin', name: 'Kartoffelgratin', emoji: '🥔', minutes: 60,
      ingredients: ['kartoffeln', 'sahne', 'kaese'], optional: ['milch', 'knoblauch', 'brokkoli', 'schinken'],
      steps: ['Kartoffeln dünn hobeln und in eine Form schichten.', 'Sahne/Milch mit Knoblauch, Salz und Muskat darübergießen, Käse obenauf.', 'Bei 180 °C ca. 45 Min. backen.'] },
    { id: 'ofengemuese', name: 'Ofengemüse mit Feta', emoji: '🥕', minutes: 40,
      ingredients: ['kartoffeln', 'paprika', 'feta'], optional: ['zucchini', 'karotten', 'zwiebeln', 'kuerbis', 'tomaten', 'joghurt'],
      steps: ['Gemüse in Stücke schneiden, mit Öl, Salz, Paprika und Kräutern mischen.', 'Bei 200 °C ca. 30 Min. rösten, Feta darüberbröseln, 5 Min. weiter backen.', 'Mit Joghurt-Dip servieren.'] },
    { id: 'kuerbissuppe', name: 'Kürbissuppe', emoji: '🎃', minutes: 35,
      ingredients: ['kuerbis', 'zwiebeln'], optional: ['karotten', 'kokosmilch', 'sahne', 'kartoffeln'],
      steps: ['Kürbis (Hokkaido mit Schale), Zwiebel und Karotte würfeln.', 'Anschwitzen, mit Brühe bedecken, 20 Min. kochen.', 'Pürieren, mit Kokosmilch oder Sahne, Ingwer und Curry abschmecken.'] },
    { id: 'gemuesesuppe', name: 'Bunte Gemüsesuppe', emoji: '🍲', minutes: 35,
      ingredients: ['karotten', 'lauch'], optional: ['kartoffeln', 'zucchini', 'erbsen', 'blumenkohl', 'nudeln', 'brokkoli', 'wurst'],
      steps: ['Gemüse klein schneiden und in Öl anschwitzen.', 'Mit Brühe aufgießen, 20 Min. köcheln.', 'Nach Belieben Suppennudeln oder Würstchen zugeben.'] },
    { id: 'linsensuppe', name: 'Rote Linsensuppe', emoji: '🥣', minutes: 30,
      ingredients: ['linsen', 'karotten'], optional: ['zwiebeln', 'kokosmilch', 'zitrone', 'passata'],
      steps: ['Zwiebel und Karotte anschwitzen, Linsen zugeben.', 'Mit Brühe auffüllen, 15 Min. kochen, pürieren.', 'Mit Kreuzkümmel, Zitrone und Kokosmilch abschmecken.'] },
    { id: 'brokkoli-auflauf', name: 'Brokkoli-Nudel-Auflauf', emoji: '🥦', minutes: 45,
      ingredients: ['brokkoli', 'nudeln', 'kaese'], optional: ['schinken', 'sahne', 'milch', 'eier'],
      steps: ['Nudeln und Brokkoli bissfest garen.', 'Mit Schinken in eine Form geben, Sahne mit Ei verquirlt darübergießen.', 'Mit Käse bestreuen, bei 200 °C 20 Min. überbacken.'] },
    { id: 'blumenkohl-kaese', name: 'Blumenkohl mit Käsesoße', emoji: '🥦', minutes: 30,
      ingredients: ['blumenkohl', 'kaese', 'milch'], optional: ['butter', 'mehl', 'kartoffeln', 'schinken'],
      steps: ['Blumenkohl in Röschen in Salzwasser garen.', 'Mehlschwitze aus Butter und Mehl, mit Milch aufgießen, Käse darin schmelzen.', 'Soße über den Blumenkohl geben.'] },
    { id: 'shakshuka', name: 'Shakshuka', emoji: '🍳', minutes: 25,
      ingredients: ['eier', 'passata', 'paprika'], optional: ['zwiebeln', 'knoblauch', 'feta', 'brot', 'tomaten'],
      steps: ['Zwiebel, Knoblauch und Paprika anbraten, mit Kreuzkümmel und Paprikapulver würzen.', 'Tomaten zugeben und 10 Min. einkochen.', 'Mulden formen, Eier hineinschlagen und zugedeckt stocken lassen. Mit Feta und Brot.'] },
    { id: 'lachs-ofen', name: 'Lachs aus dem Ofen mit Gemüse', emoji: '🐟', minutes: 30,
      ingredients: ['lachs', 'kartoffeln'], optional: ['zitrone', 'brokkoli', 'zucchini', 'sahne', 'spinat'],
      steps: ['Kartoffeln vorkochen oder klein geschnitten 15 Min. vorbacken.', 'Lachs und Gemüse dazulegen, mit Zitrone, Salz und Dill würzen.', 'Bei 200 °C ca. 15 Min. garen.'] },
    { id: 'fischpfanne', name: 'Fischfilet mit Reis und Gemüse', emoji: '🐟', minutes: 25,
      ingredients: ['fisch', 'reis'], optional: ['zitrone', 'erbsen', 'karotten', 'butter', 'spinat'],
      steps: ['Reis kochen.', 'Fischfilet salzen, in Mehl wenden und in Butter braten.', 'Gemüse dünsten, mit Zitrone servieren.'] },
    { id: 'thunfisch-pasta', name: 'Thunfisch-Tomaten-Pasta', emoji: '🐟', minutes: 20,
      ingredients: ['nudeln', 'thunfisch', 'passata'], optional: ['zwiebeln', 'mais', 'zitrone', 'knoblauch'],
      steps: ['Zwiebel und Knoblauch anschwitzen, Tomaten zugeben.', 'Thunfisch zerpflückt unterrühren, 5 Min. köcheln.', 'Mit Nudeln mischen.'] },
    { id: 'schnitzel', name: 'Schnitzel mit Kartoffelsalat', emoji: '🥩', minutes: 45,
      ingredients: ['schwein', 'eier', 'kartoffeln'], optional: ['mehl', 'brot', 'gurke', 'zitrone', 'zwiebeln'],
      steps: ['Kartoffeln kochen, schneiden, mit Brühe, Essig, Öl und Zwiebeln anmachen.', 'Schnitzel klopfen, in Mehl, Ei und Semmelbröseln wenden.', 'In reichlich Fett goldbraun braten.'] },
    { id: 'gulasch', name: 'Rindergulasch', emoji: '🥩', minutes: 120,
      ingredients: ['rind', 'zwiebeln'], optional: ['paprika', 'passata', 'kartoffeln', 'nudeln'],
      steps: ['Fleisch portionsweise scharf anbraten.', 'Viele Zwiebeln mitbraten, Paprikapulver und Tomatenmark zugeben.', 'Mit Brühe ablöschen und 1,5 Std. schmoren.'] },
    { id: 'griechischer-salat', name: 'Griechischer Salat', emoji: '🥗', minutes: 10,
      ingredients: ['tomaten', 'gurke', 'feta'], optional: ['paprika', 'zwiebeln', 'salat', 'brot'],
      steps: ['Tomaten, Gurke, Paprika und Zwiebel grob schneiden.', 'Mit Olivenöl, Essig, Oregano, Salz und Pfeffer anmachen.', 'Feta obenauf.'] },
    { id: 'caprese', name: 'Tomate-Mozzarella', emoji: '🍅', minutes: 5,
      ingredients: ['tomaten', 'mozzarella'], optional: ['pesto', 'brot', 'salat'],
      steps: ['Tomaten und Mozzarella in Scheiben schneiden.', 'Abwechselnd anrichten, mit Salz, Pfeffer, Olivenöl und Basilikum/Pesto.'] },
    { id: 'gemischter-salat', name: 'Gemischter Salat', emoji: '🥗', minutes: 10,
      ingredients: ['salat', 'tomaten'], optional: ['gurke', 'paprika', 'karotten', 'mais', 'eier', 'thunfisch', 'kaese', 'feta'],
      steps: ['Salat waschen und zupfen, Gemüse schneiden.', 'Dressing aus Öl, Essig, Senf, Salz, Pfeffer und etwas Zucker.', 'Mit Ei, Thunfisch oder Käse zur Hauptmahlzeit machen.'] },
    { id: 'zucchini-puffer', name: 'Zucchini-Puffer mit Joghurt-Dip', emoji: '🥒', minutes: 30,
      ingredients: ['zucchini', 'eier', 'mehl'], optional: ['feta', 'kaese', 'joghurt', 'knoblauch', 'karotten'],
      steps: ['Zucchini raspeln, salzen, 10 Min. ziehen lassen und ausdrücken.', 'Mit Ei, Mehl und Feta/Käse mischen.', 'Kleine Puffer goldbraun braten, Joghurt mit Knoblauch als Dip.'] },
    { id: 'pizza-toast', name: 'Pizza-Toast', emoji: '🍕', minutes: 15,
      ingredients: ['brot', 'kaese'], optional: ['schinken', 'passata', 'tomaten', 'paprika', 'champignons', 'mais', 'wurst'],
      steps: ['Brot mit Tomatenmark oder -soße bestreichen.', 'Belegen und mit Käse bestreuen.', 'Bei 200 °C ca. 10 Min. überbacken.'] },
    { id: 'kaesespaetzle', name: 'Käse-Nudeln mit Röstzwiebeln', emoji: '🧀', minutes: 25,
      ingredients: ['nudeln', 'kaese', 'zwiebeln'], optional: ['speck', 'butter', 'salat'],
      steps: ['Zwiebeln in Ringen in Butter langsam goldbraun braten.', 'Nudeln kochen und abwechselnd mit Käse in eine Pfanne/Form schichten.', 'Mit Zwiebeln servieren, dazu Salat.'] },
    { id: 'overnight-oats', name: 'Overnight Oats', emoji: '🥣', minutes: 5,
      ingredients: ['haferflocken', 'joghurt'], optional: ['milch', 'beeren', 'bananen', 'aepfel'],
      steps: ['Haferflocken mit Joghurt und Milch 1:1:1 mischen.', 'Über Nacht in den Kühlschrank stellen.', 'Mit Obst toppen.'] },
    { id: 'quark-dessert', name: 'Quarkspeise mit Obst', emoji: '🍓', minutes: 10,
      ingredients: ['quark', 'beeren'], optional: ['joghurt', 'sahne', 'bananen', 'zitrone'],
      steps: ['Quark mit Joghurt oder geschlagener Sahne glatt rühren.', 'Mit Zucker/Vanille und Zitrone abschmecken.', 'Obst unterheben oder darauf verteilen.'] },
    { id: 'smoothie', name: 'Smoothie', emoji: '🥤', minutes: 5,
      ingredients: ['bananen', 'milch'], optional: ['beeren', 'joghurt', 'haferflocken', 'spinat', 'aepfel'],
      steps: ['Alles in den Mixer geben.', 'Fein pürieren und sofort trinken – ideal für sehr reifes Obst.'] },
    { id: 'bananenbrot', name: 'Bananenbrot', emoji: '🍌', minutes: 70,
      ingredients: ['bananen', 'mehl', 'eier'], optional: ['butter', 'haferflocken', 'schokolade'],
      steps: ['3 sehr reife Bananen zerdrücken, mit 2 Eiern, 80 g Butter und 80 g Zucker verrühren.', '250 g Mehl mit 1 Pck. Backpulver unterheben.', 'In einer Kastenform bei 175 °C ca. 50 Min. backen.'] },
    { id: 'apfelkuchen', name: 'Schneller Apfelkuchen', emoji: '🍎', minutes: 60,
      ingredients: ['aepfel', 'mehl', 'eier', 'butter'], optional: ['zitrone', 'quark'],
      steps: ['Rührteig aus 200 g Butter, 150 g Zucker, 3 Eiern und 250 g Mehl mit Backpulver.', 'In die Form geben, mit Apfelspalten belegen.', 'Bei 180 °C ca. 40 Min. backen.'] },
  ];
});
